### ISSUE TITLE
no such file or directory 

### ISSUE THREAD

**Issue by LittlePigIsKid** [eNkru/electron-xiami#19]
hello developers.
i am using ubuntu 16.04's latest system.
i met this proplem  :
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/stove/.config/electron-xiami/Settings'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at Object.writeFileSync (/opt/electron-xiami/resources/app.asar/node_modules/jsonfile/index.js:117:13)
    at Settings._ensureSettings (/opt/electron-xiami/resources/app.asar/node_modules/electron-settings/lib/settings.js:179:18)
    at Settings._readSettings (/opt/electron-xiami/resources/app.asar/node_modules/electron-settings/lib/settings.js:218:10)
    at Settings._getValueAtKeyPath (/opt/electron-xiami/resources/app.asar/node_modules/electron-settings/lib/settings.js:307:22)
    at Settings.get (/opt/electron-xiami/resources/app.asar/node_modules/electron-settings/lib/settings.js:430:17)
    at Object.<anonymous> (/opt/electron-xiami/resources/app.asar/src/controller/player-controller.js:17:27)
    at Object.<anonymous> (/opt/electron-xiami/resources/app.asar/src/controller/player-controller.js:305:3)

it occurred the first time i start the software by command line after i installed it succcessfully.
i've installed the npm and git. but has nothing about the developing frame electron.
i'm not good at js at all.

wish for repling and **happy Chinese new year!!!**

**Comment by eNkru** [comment]
Does it still appear after the first launch? It basically complain the app Settings folder doesn't exist since it's the first run. The folder should be created by the electron app after the first run.

Check if you've got the folder `/home/stove/.config/electron-xiami/Settings`. If that exist, all good.

**Comment by LittlePigIsKid** [comment]
u are right.
i start the software again and i got the file named Settings. 
i can use the software now.
thank u.

**Comment by eNkru** [comment]
@LittlePigIsKid thanks for the confirmation. I'll add a checking before load the settings if the folder is not there.

Happy listening, let me know if you have any think or bug for reporting. Thank you again for supporting this project.

**Comment by eNkru** [comment]
Fixed by #ad1a37f
